### ISSUE TITLE
'module' object has no attribute 'subclassing' in django 1.10

### ISSUE THREAD

**Issue by Farcorn** [djangonauts/django-hstore#154]
I keep getting this issue after upgrading from django 1.9 to 1.10.

> 'module' object has no attribute 'subclassing'

looks like the file subclassing.py is missing in django.19
`class HStoreDescriptor(models.fields.subclassing.Creator):`

**Comment by matthewh** [comment]
+1 to this. I'm seeing the same issue with 1.10.

**Comment by shacker** [comment]
+1 - Django upgrade blocker for our team.

**Comment by nemesisdesign** [comment]
Anyone has looked into the issue and has a solution to propose?

**Comment by nemesisdesign** [comment]
Pull request #151 partially addressed this issue but some tests in the travis build are still failing. If anyone can help out, please do so.

**Comment by angelo-romano** [comment]
Hello all, experiencing this issue as well with Django 1.10, which basically makes the whole project unusable at this stage. I would say it's pretty _urgent_ and it should be fixed with high priority, given its blocking nature.

My traceback:
```
  File "/home/angelo/.virtualenvs/onback/lib/python3.5/site-packages/django_hstore/models.py", line 2, in <module>
    from .fields import DictionaryField  # noqa
  File "/home/angelo/.virtualenvs/onback/lib/python3.5/site-packages/django_hstore/fields.py", line 11, in <module>
    from .descriptors import HStoreDescriptor, HStoreReferenceDescriptor, SerializedDictDescriptor
  File "/home/angelo/.virtualenvs/onback/lib/python3.5/site-packages/django_hstore/descriptors.py", line 12, in <module>
    class HStoreDescriptor(models.fields.subclassing.Creator):
AttributeError: module 'django.db.models.fields' has no attribute 'subclassing'
```

**Comment by shacker** [comment]
@angelo-romano It looks like my team is temporarily working around this by installing from github rather than pypi (i.e. they seem to have it fixed in recent commits, but the change hasn't made it to pypi yet).

`pip install git+https://github.com/djangonauts/django-hstore.git`

**Comment by nemesisdesign** [comment]
please read #161

**Comment by Farcorn** [comment]
@nemesisdesign Please when will changes be me to pypi?

**Comment by nemesisdesign** [comment]
@Farcorn please read #161

**Comment by scheung38** [comment]
Hi this issue is still open? 

        class HStoreDescriptor(models.fields.subclassing.Creator):
     AttributeError: 'module' object has no attribute 'subclassing'

pip install git+https://github.com/djangonauts/django-hstore.git gives another error:

    "hstore type not found in the database. " 
    django.db.utils.ProgrammingError: hstore type not found in the database. please install it from 
    your 'contrib/hstore.sql' file

But where is this contrib/hstore.sql file?
