### ISSUE TITLE
Psycopg2 required version

### ISSUE THREAD

**Issue by nferrari** [djangonauts/django-hstore#28]
The register process seems not to work on a psycopg2.4 version:

"AttributeError: module object has no attribute 'new_array_type'"

Updating my psycopg2 version to last one (2.5.2) resolved the issue. Indeed, the function has been introduced in 2.4.3 version:

https://github.com/psycopg/psycopg2/blob/7b82be936dae074217b7c5b9cefe0ec2b227160c/NEWS#L153

I guess a change on prerequisites list should be ok?
